"""add_items_table

Revision ID: ff93ad097510
Revises: d85c8eba5b50
Create Date: 2026-02-13 23:05:49.197793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff93ad097510'
down_revision: Union[str, Sequence[str], None] = 'd85c8eba5b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOTE: Manually removed op.alter_column calls to avoid SQLite errors.
    # The items table creation is the only required change.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOTE: Manually removed op.alter_column calls to avoid SQLite errors.
    pass
    # ### end Alembic commands ###
